const MOCK_DEALS = [
    { id: 1, title: "A101 - Wefood Glutensiz Un", discount: "%50 İndirim", market: "A101", isPremium: false, icon: "ph-storefront" },
    { id: 2, title: "Migros - Schär Ekmek", discount: "1 Alana 1 Bedava", market: "Migros", isPremium: true, icon: "ph-shopping-cart" },
    { id: 3, title: "BİM - Karabuğday Patlağı", discount: "Stoklara Girdi (19.90 TL)", market: "BİM", isPremium: true, icon: "ph-tag" }
];

const MOCK_PRODUCTS = [
    {
        id: 1,
        name: "Glütensiz Karabuğday Patlağı",
        brand: "Wefood",
        status: "safe",
        description: "Bu ürün tamamen glütensizdir ve çölyak hastaları için güvenlidir. Üretim bandı ayrıdır."
    },
    {
        id: 2,
        name: "Sütlü Çikolata",
        brand: "X Marka",
        status: "warning",
        description: "İçeriğinde glüten yok ancak 'Eser miktarda glüten içerebilir' uyarısı mevcuttur. Çapraz bulaşma riski var."
    },
    {
        id: 3,
        name: "Yulaf Ezmesi",
        brand: "Y Marka",
        status: "danger",
        description: "Glütensiz sertifikası yoktur. Yulaf doğası gereği çapraz bulaşmaya çok müsaittir, tüketilmesi risklidir."
    },
    {
        id: 4,
        name: "Pirinç Unu",
        brand: "Glutensiz Ada",
        status: "safe",
        description: "%100 Çölyak derneği onaylı ve güvenlidir."
    }
];

// Helper to get random product for mock scanner
function getRandomMockProduct() {
    const randomIndex = Math.floor(Math.random() * MOCK_PRODUCTS.length);
    return MOCK_PRODUCTS[randomIndex];
}

const MOCK_PLACES = [
    // %100 Glutensiz Mekanlar
    { id: 1, name: "Guru Glutensiz Moda", type: "100% GF", safety: "safe", safetyScore: 99, rating: 4.9, icon: "ph-star-fill", lat: 40.9840, lng: 29.0250 },
    { id: 2, name: "d’Amalfi Senza Glutine", type: "100% GF", safety: "safe", safetyScore: 98, rating: 4.8, icon: "ph-star-fill", lat: 40.9650, lng: 29.0650 },
    { id: 3, name: "Mona Mina Suadiye", type: "100% GF", safety: "safe", safetyScore: 100, rating: 4.9, icon: "ph-star-fill", lat: 40.9610, lng: 29.0830 },
    { id: 4, name: "Tatlı Fırın Cadde", type: "100% GF", safety: "safe", safetyScore: 95, rating: 4.7, icon: "ph-star-fill", lat: 40.9570, lng: 29.0910 },
    { id: 5, name: "Tatlı Fırın Ataköy", type: "100% GF", safety: "safe", safetyScore: 94, rating: 4.6, icon: "ph-star-fill", lat: 40.9850, lng: 28.8450 },
    { id: 6, name: "Glutensiz.com Etiler", type: "100% GF", safety: "safe", safetyScore: 99, rating: 4.9, icon: "ph-star-fill", lat: 41.0820, lng: 29.0320 },
    { id: 7, name: "Rolla GlutenFree", type: "100% GF", safety: "safe", safetyScore: 97, rating: 4.8, icon: "ph-star-fill", lat: 40.9880, lng: 29.0210 },
    { id: 8, name: "Guru Glutensiz", type: "100% GF", safety: "safe", safetyScore: 99, rating: 4.9, icon: "ph-star-fill", lat: 40.9820, lng: 29.0270 },
    
    // GF Seçeneği Sunan Mekanlar
    { id: 9, name: "Cafe Amedros", type: "Seçenek Sunar", safety: "warning", safetyScore: 65, rating: 4.3, icon: "ph-warning-circle", lat: 41.0080, lng: 28.9770 },
    { id: 10, name: "Arch Bistro", type: "Seçenek Sunar", safety: "warning", safetyScore: 70, rating: 4.5, icon: "ph-warning-circle", lat: 41.0050, lng: 28.9760 },
    { id: 11, name: "Suad Restaurant", type: "Seçenek Sunar", safety: "warning", safetyScore: 68, rating: 4.4, icon: "ph-warning-circle", lat: 40.9620, lng: 29.0800 },
    { id: 12, name: "Vegan Dükkan Lokanta", type: "Seçenek Sunar", safety: "warning", safetyScore: 85, rating: 4.6, icon: "ph-warning-circle", lat: 41.0310, lng: 28.9810 },
    { id: 13, name: "Enjoy Cafe", type: "Kafe & Fırın", safety: "warning", safetyScore: 60, rating: 4.2, icon: "ph-warning-circle", lat: 41.0380, lng: 28.9830 },
    { id: 14, name: "Zencefil Restaurant", type: "Kafe & Fırın", safety: "warning", safetyScore: 75, rating: 4.3, icon: "ph-warning-circle", lat: 41.0360, lng: 28.9800 }
];

const MOCK_RECIPES = [
  { id: 1, name: "Glutensiz Lahmacun", category: "ana_yemek", prep_time: "45 dk", difficulty: "orta", calories: 280, protein: "12g", carbs: "35g", fat: "10g", image: "https://source.unsplash.com/featured/?lahmacun,pizza", ingredients: ["glutensiz un", "kıyma", "soğan", "domates", "biber salçası"], steps: ["Hamuru yoğur ve aç", "İç harcı hazırla", "Hamurun üzerine yay", "Fırında pişir"] },
  { id: 2, name: "Glutensiz Mantı", category: "ana_yemek", prep_time: "60 dk", difficulty: "zor", calories: 350, protein: "15g", carbs: "45g", fat: "12g", image: "https://source.unsplash.com/featured/?ravioli,manti", ingredients: ["karabuğday unu", "kıyma", "soğan", "yoğurt", "tereyağı", "nane"], steps: ["Hamuru aç ve kes", "Kıymalı harcı koy ve kapat", "Suda haşla", "Sarımsaklı yoğurt ve sosla servis yap"] },
  { id: 3, name: "Zeytinyağlı Yaprak Sarma", category: "meze", prep_time: "50 dk", difficulty: "orta", calories: 210, protein: "3g", carbs: "35g", fat: "8g", image: "https://source.unsplash.com/featured/?stuffed-grape-leaves", ingredients: ["asma yaprağı", "pirinç", "soğan", "zeytinyağı", "nane", "kuş üzümü"], steps: ["İç harcı kavur", "Yaprakları sar", "Tencereye diz ve pişir"] },
  { id: 4, name: "Hünkar Beğendi", category: "ana_yemek", prep_time: "45 dk", difficulty: "orta", calories: 380, protein: "22g", carbs: "15g", fat: "25g", image: "https://source.unsplash.com/featured/?meat-stew,eggplant", ingredients: ["kuzu eti", "patlıcan", "tereyağı", "glutensiz un", "süt", "kaşar peyniri"], steps: ["Etleri sotele", "Patlıcanı közle ve püre yap", "Glutensiz unla beşamel hazırla", "Patlıcanla birleştirip eti üzerine ekle"] },
  { id: 5, name: "Glutensiz Pide (Kıymalı)", category: "ana_yemek", prep_time: "50 dk", difficulty: "orta", calories: 320, protein: "16g", carbs: "40g", fat: "11g", image: "https://source.unsplash.com/featured/?turkish-pide", ingredients: ["glutensiz un karışımı", "maya", "kıyma", "domates", "biber"], steps: ["Hamuru mayala", "Kayık şeklinde aç", "İç harcı yay", "Fırınla"] },
  { id: 6, name: "Tarhana Çorbası", category: "çorba", prep_time: "20 dk", difficulty: "kolay", calories: 160, protein: "6g", carbs: "25g", fat: "4g", image: "https://source.unsplash.com/featured/?soup", ingredients: ["glutensiz tarhana", "tereyağı", "nane", "su", "salça"], steps: ["Tarhanayı suda çöz", "Salça ve yağı kavur", "Tarhanayı ekleyip kaynat"] },
  { id: 7, name: "İmambayıldı", category: "ana_yemek", prep_time: "45 dk", difficulty: "orta", calories: 190, protein: "4g", carbs: "14g", fat: "15g", image: "https://source.unsplash.com/featured/?eggplant-dish", ingredients: ["patlıcan", "soğan", "sarımsak", "domates", "zeytinyağı"], steps: ["Patlıcanları alacalı soy ve kızart", "İç harcı kavur", "Patlıcanların içine doldur ve fırınla"] },
  { id: 8, name: "Mücver (Glutensiz Unlu)", category: "meze", prep_time: "25 dk", difficulty: "kolay", calories: 210, protein: "7g", carbs: "16g", fat: "13g", image: "https://source.unsplash.com/featured/?zucchini-fritters", ingredients: ["kabak", "yumurta", "glutensiz un", "dereotu", "beyaz peynir"], steps: ["Kabağı rendele ve suyunu sık", "Malzemeleri karıştır", "Az yağda kızart"] },
  { id: 9, name: "Ali Nazik", category: "ana_yemek", prep_time: "40 dk", difficulty: "orta", calories: 310, protein: "20g", carbs: "12g", fat: "20g", image: "https://source.unsplash.com/featured/?kebab,yogurt", ingredients: ["kıyma", "patlıcan", "süzme yoğurt", "sarımsak", "tereyağı", "pul biber"], steps: ["Patlıcanı közle ve ez", "Sarımsaklı yoğurtla karıştır", "Kıymayı kavur", "Yoğurtlu yatağın üzerine kıymayı ekle"] },
  { id: 10, name: "Çılbır", category: "kahvaltı", prep_time: "15 dk", difficulty: "kolay", calories: 230, protein: "14g", carbs: "5g", fat: "18g", image: "https://source.unsplash.com/featured/?poached-egg,yogurt", ingredients: ["yumurta", "süzme yoğurt", "sarımsak", "tereyağı", "toz biber"], steps: ["Yoğurdu sarımsakla çırp", "Yumurtaları poşe tekniğiyle haşla", "Yoğurdun üzerine yumurtaları koy", "Kızgın tereyağı dök"] },
  { id: 11, name: "Fırın Sütlaç", category: "tatlı", prep_time: "45 dk", difficulty: "orta", calories: 280, protein: "7g", carbs: "48g", fat: "6g", image: "https://source.unsplash.com/featured/?baked-rice-pudding", ingredients: ["süt", "pirinç", "şeker", "mısır nişastası", "vanilya"], steps: ["Pirinci haşla", "Süt ve şekeri ekle kaynat", "Nişasta ile bağla", "Güveçlere paylaştırıp fırında üstünü kızart"] },
  { id: 12, name: "Şakşuka", category: "meze", prep_time: "30 dk", difficulty: "kolay", calories: 200, protein: "3g", carbs: "18g", fat: "14g", image: "https://source.unsplash.com/featured/?shakshuka,eggplant", ingredients: ["patlıcan", "kabak", "biber", "domates", "sarımsak", "zeytinyağı"], steps: ["Sebzeleri küp küp doğra ve kızart", "Domates sosunu hazırla", "Kızarmış sebzeleri sosla buluştur"] },
  { id: 13, name: "Zeytinyağlı Enginar", category: "ana_yemek", prep_time: "35 dk", difficulty: "kolay", calories: 160, protein: "4g", carbs: "20g", fat: "8g", image: "https://source.unsplash.com/featured/?artichoke", ingredients: ["enginar kalbi", "havuç", "patates", "bezelye", "zeytinyağı", "limon", "dereotu"], steps: ["Garnitürü hazırla", "Enginarları tencereye diz", "Üzerine garnitür ekle, yağ ve limon suyu ile pişir"] },
  { id: 14, name: "Tepsi Kebabı", category: "ana_yemek", prep_time: "45 dk", difficulty: "orta", calories: 360, protein: "28g", carbs: "8g", fat: "24g", image: "https://source.unsplash.com/featured/?kebab,meat", ingredients: ["dana kıyma", "soğan", "sarımsak", "kapya biber", "maydanoz", "domates salçası"], steps: ["Kıymayı sebzelerle yoğur", "Tepsiye yay", "Üzerine salçalı su döküp fırınla"] },
  { id: 15, name: "Glutensiz Revani", category: "tatlı", prep_time: "40 dk", difficulty: "orta", calories: 340, protein: "6g", carbs: "55g", fat: "12g", image: "https://source.unsplash.com/featured/?semolina-cake", ingredients: ["glutensiz irmik", "glutensiz un", "yumurta", "yoğurt", "şeker", "sıvı yağ", "şerbet"], steps: ["Kek harcını hazırla ve fırınla", "Şerbeti kaynat ve soğut", "Sıcak keke soğuk şerbeti dök"] },
  { id: 16, name: "Barbunya Pilaki", category: "meze", prep_time: "40 dk", difficulty: "kolay", calories: 190, protein: "8g", carbs: "30g", fat: "5g", image: "https://source.unsplash.com/featured/?beans-stew", ingredients: ["taze barbunya", "havuç", "patates", "soğan", "sarımsak", "zeytinyağı"], steps: ["Sebzeleri sotele", "Barbunyaları ekle", "Su ekleyip yumuşayana kadar pişir", "Soğuk servis yap"] },
  { id: 17, name: "Kısır (Kinoa ile)", category: "salata", prep_time: "20 dk", difficulty: "kolay", calories: 240, protein: "8g", carbs: "35g", fat: "9g", image: "https://source.unsplash.com/featured/?quinoa-salad", ingredients: ["kinoa", "domates salçası", "biber salçası", "yeşil soğan", "maydanoz", "nar ekşisi", "zeytinyağı"], steps: ["Kinoayı haşla", "Salçalarla yoğur", "Yeşillikleri ve sosları ekleyip karıştır"] },
  { id: 18, name: "Yayla Çorbası", category: "çorba", prep_time: "25 dk", difficulty: "kolay", calories: 170, protein: "7g", carbs: "22g", fat: "6g", image: "https://source.unsplash.com/featured/?yogurt-soup", ingredients: ["yoğurt", "pirinç", "yumurta", "glutensiz un (terbiye için)", "nane", "tereyağı"], steps: ["Pirinci haşla", "Yoğurt, yumurta ve unla terbiye hazırla", "Çorbaya alıştırarak ekle", "Üzerine naneli yağ gezdir"] },
  { id: 19, name: "Kuru Fasulye", category: "ana_yemek", prep_time: "60 dk", difficulty: "kolay", calories: 280, protein: "14g", carbs: "38g", fat: "8g", image: "https://source.unsplash.com/featured/?white-beans,stew", ingredients: ["kuru fasulye", "kuru soğan", "domates salçası", "tereyağı", "dana eti (isteğe bağlı)"], steps: ["Fasulyeleri geceden ıslat ve haşla", "Soğan ve salçayı kavur", "Fasulyeleri ve suyu ekleyip özleşene kadar pişir"] },
  { id: 20, name: "Fırında Somon", category: "ana_yemek", prep_time: "25 dk", difficulty: "kolay", calories: 320, protein: "28g", carbs: "2g", fat: "22g", image: "https://source.unsplash.com/featured/?baked-salmon", ingredients: ["somon fileto", "zeytinyağı", "limon", "sarımsak", "karabiber"], steps: ["Somonu sosla marine et", "Fırın tepsisine diz", "200 derecede 15-20 dk pişir"] },
  { id: 21, name: "Glutensiz İrmik Helvası", category: "tatlı", prep_time: "30 dk", difficulty: "orta", calories: 350, protein: "5g", carbs: "48g", fat: "15g", image: "https://source.unsplash.com/featured/?semolina,dessert", ingredients: ["glutensiz irmik", "tereyağı", "çam fıstığı", "süt", "su", "şeker"], steps: ["Süt, su ve şekeri kaynat", "Tereyağında fıstık ve irmiği kavur", "Şerbeti döküp demlenmeye bırak"] },
  { id: 22, name: "Humus", category: "meze", prep_time: "15 dk", difficulty: "kolay", calories: 220, protein: "8g", carbs: "18g", fat: "14g", image: "https://source.unsplash.com/featured/?hummus", ingredients: ["haşlanmış nohut", "tahin", "limon suyu", "sarımsak", "zeytinyağı", "kimyon"], steps: ["Tüm malzemeleri blenderdan pürüzsüz olana kadar geçir", "Zeytinyağı ve pul biberle servis yap"] },
  { id: 23, name: "Etli Ekmek (Glutensiz)", category: "ana_yemek", prep_time: "50 dk", difficulty: "orta", calories: 340, protein: "18g", carbs: "38g", fat: "12g", image: "https://source.unsplash.com/featured/?flatbread,meat", ingredients: ["glutensiz un", "maya", "kıyma", "domates", "sivri biber", "soğan"], steps: ["Hamuru yoğur", "İnce uzun aç", "Kıymalı harcı çiğden yay", "Yüksek ateşte fırınla"] },
  { id: 24, name: "Domates Çorbası", category: "çorba", prep_time: "20 dk", difficulty: "kolay", calories: 140, protein: "4g", carbs: "15g", fat: "8g", image: "https://source.unsplash.com/featured/?tomato-soup", ingredients: ["domates rendesi", "glutensiz un", "tereyağı", "süt", "kaşar peyniri"], steps: ["Unu tereyağında kavur", "Domatesi ekle ve pişir", "Süt ile kıvam aç", "Kaşar peyniriyle servis et"] },
  { id: 25, name: "Kabak Sıyırma", category: "zeytinyağlı", prep_time: "25 dk", difficulty: "kolay", calories: 110, protein: "2g", carbs: "12g", fat: "6g", image: "https://source.unsplash.com/featured/?zucchini,olive-oil", ingredients: ["kabak", "soğan", "zeytinyağı", "dereotu", "limon"], steps: ["Kabakları ince şeritler halinde kes", "Soğanla sotele", "Dereotu ve limonla soğuk servis yap"] },
  { id: 26, name: "Tas Kebabı", category: "ana_yemek", prep_time: "60 dk", difficulty: "orta", calories: 330, protein: "26g", carbs: "15g", fat: "18g", image: "https://source.unsplash.com/featured/?meat-stew,beef", ingredients: ["dana kuşbaşı", "patates", "havuç", "soğan", "domates salçası", "tereyağı"], steps: ["Eti kavur", "Sebzeleri doğrayıp ekle", "Salça ve sıcak su ekleyerek kısık ateşte pişir"] },
  { id: 27, name: "Gavurdağı Salatası", category: "salata", prep_time: "15 dk", difficulty: "kolay", calories: 180, protein: "3g", carbs: "14g", fat: "12g", image: "https://source.unsplash.com/featured/?turkish-salad", ingredients: ["domates", "kuru soğan", "ceviz", "maydanoz", "nar ekşisi", "zeytinyağı"], steps: ["Malzemeleri çok küçük doğra", "Ceviz, nar ekşisi ve zeytinyağı ile harmanla"] },
  { id: 28, name: "Glutensiz Güllaç", category: "tatlı", prep_time: "20 dk", difficulty: "kolay", calories: 260, protein: "8g", carbs: "45g", fat: "6g", image: "https://source.unsplash.com/featured/?milky-dessert", ingredients: ["mısır nişastası bazlı glutensiz güllaç yaprağı", "süt", "şeker", "ceviz", "gül suyu"], steps: ["Sütü şekerle ılıt", "Yaprakları sütle ıslatarak tepsiye diz", "Araya ceviz serpiştir", "Soğuk servis yap"] },
  { id: 29, name: "Ezmogelin Çorbası", category: "çorba", prep_time: "30 dk", difficulty: "kolay", calories: 190, protein: "9g", carbs: "30g", fat: "5g", image: "https://source.unsplash.com/featured/?lentil-soup,spicy", ingredients: ["kırmızı mercimek", "pirinç", "nane", "pul biber", "soğan", "salça", "tereyağı"], steps: ["Mercimek ve pirinci soğanla kaynat", "Blenderdan çek (isteğe bağlı)", "Naneli salçalı sos yapıp ekle"] },
  { id: 30, name: "Kıymalı Yumurta", category: "kahvaltı", prep_time: "15 dk", difficulty: "kolay", calories: 270, protein: "18g", carbs: "2g", fat: "21g", image: "https://source.unsplash.com/featured/?minced-meat,egg", ingredients: ["kıyma", "soğan", "yumurta", "tereyağı", "karabiber"], steps: ["Kıymayı ve soğanı kavur", "Üzerine yumurtaları kır", "Kapak kapatıp pişir"] },
  { id: 31, name: "Glutensiz Sigara Böreği", category: "ara_sıcak", prep_time: "30 dk", difficulty: "orta", calories: 220, protein: "7g", carbs: "25g", fat: "10g", image: "https://source.unsplash.com/featured/?cheese-rolls", ingredients: ["glutensiz yufka", "beyaz peynir", "maydanoz", "sıvı yağ (kızartmak için)"], steps: ["Yufkaları üçgen kes", "Peynirli harcı koyup sar", "Kızgın yağda kızart"] },
  { id: 32, name: "Patlıcan Musakka", category: "ana_yemek", prep_time: "45 dk", difficulty: "orta", calories: 310, protein: "16g", carbs: "12g", fat: "22g", image: "https://source.unsplash.com/featured/?eggplant,meat", ingredients: ["patlıcan", "kıyma", "soğan", "domates", "biber", "salça"], steps: ["Patlıcanları halka kesip hafif kızart", "Kıymalı harcı hazırla", "Tencereye dizip harcı ekle, pişir"] },
  { id: 33, name: "Glutensiz Su Böreği", category: "ana_yemek", prep_time: "75 dk", difficulty: "zor", calories: 380, protein: "12g", carbs: "40g", fat: "18g", image: "https://source.unsplash.com/featured/?pastry,cheese", ingredients: ["glutensiz un", "yumurta", "beyaz peynir", "tereyağı", "tuz"], steps: ["Hamur yoğur ve bezeler yap", "Bezeleri açıp suda haşla", "Aralarına peynir ve yağ sürerek tepsiye diz", "Fırında veya ocakta pişir"] },
  { id: 34, name: "Kereviz Salatası", category: "meze", prep_time: "15 dk", difficulty: "kolay", calories: 140, protein: "4g", carbs: "10g", fat: "9g", image: "https://source.unsplash.com/featured/?celery-salad", ingredients: ["kereviz", "süzme yoğurt", "mayonez", "ceviz", "sarımsak"], steps: ["Kerevizi rendele", "Yoğurt, sarımsak ve cevizle hemen karıştır (kararmaması için)"] },
  { id: 35, name: "Hamsi Tava (Mısır Unlu)", category: "ana_yemek", prep_time: "25 dk", difficulty: "kolay", calories: 290, protein: "25g", carbs: "8g", fat: "16g", image: "https://source.unsplash.com/featured/?fried-fish", ingredients: ["hamsi", "glutensiz mısır unu", "tuz", "sıvı yağ"], steps: ["Hamsileri temizle ve yıka", "Mısır ununa bula", "Tavada çift taraflı kızart"] },
  { id: 36, name: "Glutensiz Şekerpare", category: "tatlı", prep_time: "40 dk", difficulty: "orta", calories: 360, protein: "4g", carbs: "50g", fat: "15g", image: "https://source.unsplash.com/featured/?turkish-dessert", ingredients: ["glutensiz un", "glutensiz irmik", "tereyağı", "pudra şekeri", "yumurta", "fındık", "şerbet"], steps: ["Hamuru yoğur ve şekil ver", "Üzerine fındık koyup fırınla", "Sıcak tatlıya ılık şerbet dök"] },
  { id: 37, name: "Zeytinyağlı Pırasa", category: "zeytinyağlı", prep_time: "30 dk", difficulty: "kolay", calories: 130, protein: "2g", carbs: "16g", fat: "7g", image: "https://source.unsplash.com/featured/?leek-stew", ingredients: ["pırasa", "havuç", "pirinç", "zeytinyağı", "limon suyu", "kesme şeker"], steps: ["Sebzeleri doğra", "Zeytinyağında hafif kavur", "Pirinç, su ve limon suyu ekleyip pişir"] },
  { id: 38, name: "Mıhlama (Kuymak)", category: "kahvaltı", prep_time: "15 dk", difficulty: "orta", calories: 420, protein: "15g", carbs: "10g", fat: "35g", image: "https://source.unsplash.com/featured/?melted-cheese,corn-flour", ingredients: ["tereyağı", "glutensiz mısır unu", "kolot veya telli peynir", "su"], steps: ["Tereyağını erit", "Mısır ununu kavur", "Sıcak su ekleyip kaynat", "Peyniri ekle ve uzayana kadar bekle"] },
  { id: 39, name: "Glutensiz Simit", category: "kahvaltı", prep_time: "60 dk", difficulty: "zor", calories: 280, protein: "5g", carbs: "45g", fat: "8g", image: "https://source.unsplash.com/featured/?bagel,sesame", ingredients: ["glutensiz un", "maya", "susam", "pekmez", "su"], steps: ["Hamuru yoğur ve mayala", "Simit şekli ver", "Sulandırılmış pekmeze batır, sonra susama bula", "Fırınla"] },
  { id: 40, name: "Kabak Tatlısı", category: "tatlı", prep_time: "45 dk", difficulty: "kolay", calories: 210, protein: "1g", carbs: "45g", fat: "4g", image: "https://source.unsplash.com/featured/?pumpkin-dessert", ingredients: ["balkabağı", "toz şeker", "ceviz", "tahin (isteğe bağlı)"], steps: ["Kabakları şekerle beklet", "Kendi suyunda kısık ateşte pişir", "Ceviz ve tahinle servis et"] },
  { id: 41, name: "Glutensiz Kayseri Yağlaması", category: "ana_yemek", prep_time: "60 dk", difficulty: "zor", calories: 410, protein: "18g", carbs: "42g", fat: "18g", image: "https://source.unsplash.com/featured/?flatbread,minced-meat", ingredients: ["glutensiz lavaş hamuru", "kıyma", "soğan", "salça", "domates", "sarımsaklı yoğurt"], steps: ["Lavaşları tavada pişir", "Kıymalı sulu harcı hazırla", "Lavaş ve kıymayı kat kat diz", "Sarımsaklı yoğurtla servis yap"] },
  { id: 42, name: "Fava (Bakla Ezmesi)", category: "meze", prep_time: "45 dk", difficulty: "kolay", calories: 180, protein: "9g", carbs: "22g", fat: "7g", image: "https://source.unsplash.com/featured/?fava-beans", ingredients: ["kuru iç bakla", "soğan", "zeytinyağı", "dereotu", "şeker", "limon"], steps: ["Baklayı soğanla haşla", "Blenderdan geçir", "Kalıba döküp dondur", "Zeytinyağı ve dereotuyla servis yap"] },
  { id: 43, name: "Çiğ Köfte (Etsiz)", category: "meze", prep_time: "40 dk", difficulty: "orta", calories: 220, protein: "6g", carbs: "35g", fat: "7g", image: "https://source.unsplash.com/featured/?turkish-spicy-bulgur", ingredients: ["haşlanmış kinoa veya ince karabuğday", "domates ve biber salçası", "isot", "nar ekşisi", "ceviz", "soğan"], steps: ["Malzemeleri geniş tepside yoğur", "Yeşilliklerle servis et"] },
  { id: 44, name: "Köz Patlıcan Salatası", category: "meze", prep_time: "20 dk", difficulty: "kolay", calories: 110, protein: "2g", carbs: "10g", fat: "7g", image: "https://source.unsplash.com/featured/?roasted-eggplant", ingredients: ["patlıcan", "kırmızı biber", "sarımsak", "zeytinyağı", "limon", "maydanoz"], steps: ["Patlıcan ve biberi közle", "Kabuklarını soyup ince doğra", "Sarımsak, limon ve yağla karıştır"] },
  { id: 45, name: "Glutensiz Profiterol", category: "tatlı", prep_time: "60 dk", difficulty: "zor", calories: 380, protein: "8g", carbs: "40g", fat: "20g", image: "https://source.unsplash.com/featured/?profiterole", ingredients: ["glutensiz un", "yumurta", "tereyağı", "su", "krema için süt ve mısır nişastası", "çikolata sosu"], steps: ["Pate a choux hamurunu yap ve fırınla", "Kremayı pişir ve içlerini doldur", "Çikolata sosu dök"] },
  { id: 46, name: "Tavuk Sote", category: "ana_yemek", prep_time: "25 dk", difficulty: "kolay", calories: 270, protein: "28g", carbs: "8g", fat: "12g", image: "https://source.unsplash.com/featured/?chicken-stew", ingredients: ["tavuk göğsü", "soğan", "yeşil biber", "domates", "baharatlar", "zeytinyağı"], steps: ["Tavukları sotele", "Sebzeleri ekle", "Kendi suyunda pişir"] },
  { id: 47, name: "Zeytinyağlı Bamya", category: "zeytinyağlı", prep_time: "35 dk", difficulty: "orta", calories: 140, protein: "3g", carbs: "14g", fat: "8g", image: "https://source.unsplash.com/featured/?okra", ingredients: ["taze bamya", "soğan", "domates", "zeytinyağı", "limon", "su"], steps: ["Bamyaları ayıkla", "Soğan ve domatesi kavur", "Bamyaları ekleyip asitle (limon) pişir"] },
  { id: 48, name: "Glutensiz Ekmek Kadayıfı", category: "tatlı", prep_time: "50 dk", difficulty: "zor", calories: 410, protein: "4g", carbs: "65g", fat: "12g", image: "https://source.unsplash.com/featured/?bread-dessert,kaymak", ingredients: ["glutensiz hazır kadayıf", "şeker", "su", "kaymak", "ceviz"], steps: ["Karamelli şerbet hazırla", "Kadayıfı şerbetle pişir", "Soğuyunca arasına kaymak koy"] },
  { id: 49, name: "İzmir Köfte", category: "ana_yemek", prep_time: "45 dk", difficulty: "orta", calories: 340, protein: "22g", carbs: "16g", fat: "20g", image: "https://source.unsplash.com/featured/?meatballs,potato", ingredients: ["kıyma", "patates", "domates salçası", "biber", "domates"], steps: ["Köfteyi ve patatesi hafif kızart", "Tepsiye diz", "Salçalı sos döküp fırınla"] },
  { id: 50, name: "Su Muhallebisi", category: "tatlı", prep_time: "20 dk", difficulty: "kolay", calories: 180, protein: "5g", carbs: "30g", fat: "4g", image: "https://source.unsplash.com/featured/?pudding,rose-water", ingredients: ["süt", "su", "mısır nişastası", "şeker", "gül suyu", "pudra şekeri"], steps: ["Tüm malzemeleri karıştırarak pişir", "Tepsiye döküp dondur", "Kare kesip üzerine gül suyu ve pudra şekeri ekle"] }
];
